---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  environment:
  working_directory: ~/project

version: 2
jobs:
  run-tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - run:
          name: Run tests
          command: yarn test
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  check-prettier:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - run:
          name: Run tests
          command: yarn prettier --check 'src/**/*'
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  check-eslint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - run:
          name: Run linter
          command: yarn run eslint-check
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
workflows:
  version: 2
  build:
    jobs:
      - run-tests
      - check-prettier
      - check-eslint
