---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  environment:
  working_directory: ~/project

version: 2
jobs:
  run-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run tests
          command: yarn test
  check-prettier:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run tests
          command: yarn prettier --check 'src/**/*'
  check-eslint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run linter
          command: yarn run eslint-check
workflows:
  version: 2
  build:
    jobs:
      - run-tests
      - check-prettier
