name: "E2E tests: JIMM, Docker dashboard and Keycloak"

on:
  workflow_call:
    inputs:
      admin-username:
        required: false
        type: string
        description: The username to use when logging in as the admin user.
        default: admin
      admin-password:
        required: false
        type: string
        description: The password to use when logging in as the admin user.
        default: test

permissions: read-all

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout Juju Dashboard repo
        uses: actions/checkout@v6
      - name: Configure action
        id: config
        uses: ./.github/actions/prepare-action
      - name: Set up Juju Dashboard Docker image
        id: docker-dashboard
        uses: ./.github/actions/setup-docker-dashboard
        with:
          dashboard-ref: ${{ github.ref }} # Use the dashboard version from this branch.
          run: true
          is-juju: false
          controller-ws-address: ws://jimm.localhost:17070
      - name: Checkout JIMM repo
        uses: actions/checkout@v6
        with:
          repository: canonical/jimm
          path: jimm
      - name: Update JIMM with the dashboard address
        run: |
          sudo snap install yq
          yq -i '.services.jimm-base.environment.JIMM_DASHBOARD_FINAL_REDIRECT_URL = "http://${{ steps.docker-dashboard.outputs.address }}"' jimm/docker-compose.common.yaml
          yq -i '.services.jimm-base.environment.JIMM_DASHBOARD_LOCATION = "http://${{ steps.docker-dashboard.outputs.address }}"' jimm/docker-compose.common.yaml
          yq -i '.services.jimm-base.environment.CORS_ALLOWED_ORIGINS = "http://${{ steps.docker-dashboard.outputs.address }}"' jimm/docker-compose.common.yaml
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "jimm/go.mod"
      - name: Go vendor to speed up docker build
        run: cd jimm && go mod vendor
      - name: Start JIMM (pull request)
        uses: ./jimm/.github/actions/test-server
        with:
          jimm-version: v3.2.2
          juju-channel: "3.6/stable"
          ghcr-pat: ${{ secrets.GITHUB_TOKEN }}
          dump-logs: true
      - name: Set the CLI admin's password
        run: |
          juju switch ${{ env.CONTROLLER_NAME }}
          echo '${{ inputs.admin-password }}' | juju change-user-password --no-prompt
      - name: Restart JIMM
        run: docker restart jimm-test # Fixes a context cancelled issue when fetching models from the dashboard.
      - name: Wait for JIMM container to be ready
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 1
          max_attempts: 2
          command: while [ "$(docker inspect -f {{.State.Restarting}} jimm-test)" == "true" ]; do sleep 1; done
      - name: Install jaas plugin
        run: sudo snap install jaas
      - name: Run tests
        uses: ./.github/actions/run-playwright
        with:
          test-identifier: e2e-jimm-docker-keycloak
        env:
          JIMM_CONTROLLER_NAME: ${{ env.CONTROLLER_NAME }}
          CONTROLLER_NAME: jimm
          DASHBOARD_ADDRESS: http://${{ steps.docker-dashboard.outputs.address }}
          AUTH_MODE: oidc
          AUTH_VARIANT: keycloak
          JUJU_ENV: jimm
          PROVIDER: localhost
          ADMIN_USERNAME: ${{ inputs.admin-username }}
          ADMIN_PASSWORD: ${{ inputs.admin-password }}
          ADMIN_IDENTITY_USERNAME: jimm-test@canonical.com
          ADMIN_IDENTITY_PASSWORD: password
      - name: Display logs
        if: failure()
        uses: ./.github/actions/failure-log
        with:
          juju-env: "juju"
          controller: ${{ env.CONTROLLER_NAME }}
      - name: Send notification on failure
        if: steps.config.outputs.send-failure-notification && failure()
        uses: ./.github/actions/send-notification
        with:
          webhook-url: ${{ secrets.WEBBOT_URL }}
