name: "E2E tests: Juju, k8s charm and local auth"

on:
  workflow_call:
    inputs:
      admin-password:
        required: false
        type: string
        description: The password to use when logging in as the admin user.
        default: password1

permissions: read-all

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout Juju Dashboard repo
        uses: actions/checkout@v4
      - name: Configure action
        id: config
        uses: ./.github/actions/prepare-action
      - name: Setup Juju controller on k8s
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: "microk8s"
          channel: 1.32-strict/stable
          juju-channel: ${{ steps.config.outputs.juju-channel }}
          microk8s-group: snap_microk8s
      - name: Save microk8s controller name
        id: microk8s-controller
        run: echo "name=$CONTROLLER_NAME" >> "$GITHUB_OUTPUT"
        shell: bash
      - name: Set up access
        run: echo '${{ inputs.admin-password }}' | juju change-user-password --no-prompt
      - name: Set up Juju Dashboard k8s charm
        uses: ./.github/actions/setup-k8s-charm
        with:
          dashboard-ref: ${{ steps.config.outputs.repo-ref }}
          dashboard-resource: ${{ steps.config.outputs.k8s-dashboard-resource }}
          charm-channel: ${{ steps.config.outputs.dashboard-charm-channel }}
          dashboard-charm-ref: ${{ steps.config.outputs.dashboard-charm-ref }}
      - name: Run tests
        uses: ./.github/actions/run-playwright
        with:
          test-identifier: e2e-juju-k8s-charm-local-auth
        env:
          CONTROLLER_NAME: ${{ steps.microk8s-controller.outputs.name }}
          AUTH_MODE: local
          JUJU_ENV: juju
          PROVIDER: microk8s
          ADMIN_USERNAME: admin
          ADMIN_PASSWORD: ${{ inputs.admin-password }}
      - name: Display logs
        if: failure()
        uses: ./.github/actions/failure-log
        with:
          juju-env: "juju"
          controller: ${{ steps.microk8s-controller.outputs.name }}
      - name: Send notification on failure
        if: steps.config.outputs.send-failure-notification && failure()
        uses: ./.github/actions/send-notification
        with:
          webhook-url: ${{ secrets.WEBBOT_URL }}
