name: End-to-end tests
on:
  pull_request:
    branches:
      - main
jobs:
  juju-machine-local:
    name: Test Juju, machine-charm and local-auth
    uses: ./.github/workflows/e2e-juju-machine-charm-local-auth.yml
    secrets: inherit
  juju-machine-candid:
    name: Test Juju, machine-charm and candid-auth
    uses: ./.github/workflows/e2e-juju-machine-charm-candid-auth.yml
    secrets: inherit
  juju-k8s-local:
    name: Test Juju, k8s-charm and local-auth
    uses: ./.github/workflows/e2e-juju-k8s-charm-local-auth.yml
    secrets: inherit
  jimm-machine:
    name: Test JIMM, machine charm and OIDC
    uses: ./.github/workflows/e2e-jimm-machine-charm-oidc.yml
    secrets: inherit
