name: Upload TICS report
on:
  schedule:
    - cron: "0 22 * * 5"
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - update-tics-runner # Remove before merge
permissions: read-all

jobs:
  TICS:
    runs-on: [self-hosted, linux, amd64, tiobe, noble]
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install
        run: yarn install --immutable
      - run: yarn test --coverage.enabled true
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: juju-dashboard-coverage
          path: coverage
      - name: Run TICS analysis with github-action
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: juju-dashboard
          branchdir: .
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
          tmpdir: /tmp/tics
          additionalFlags: -archivefile '${{ github.workspace }}/.github/workflows/tiobe_archive.txt'
